"""empty message

Revision ID: b9fbc599c9a2
Revises: ce9f11292ea3
Create Date: 2021-10-25 20:31:27.108187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9fbc599c9a2'
down_revision = 'ce9f11292ea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment', sa.Column('complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessment', 'complete')
    # ### end Alembic commands ###
