"""modified model

Revision ID: ce9f11292ea3
Revises: e2664ef62ea9
Create Date: 2021-10-25 20:29:22.055493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce9f11292ea3'
down_revision = 'e2664ef62ea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment', sa.Column('complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessment', 'complete')
    # ### end Alembic commands ###
